import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "p1",
    name: "Apex Exterior Emulsion",
    slug: "apex-exterior-emulsion-20l",
    brand: "Asian Paints",
    category: "Exterior Paints",
    finish: "Matt",
    size: "20",
    unit: "L",
    price: 6450,
    stock: 18,
    tintable: true,
    status: "active",
    isFeatured: true,
    isVisibleOnStorefront: true,
    shortDescription: "Durable exterior emulsion for long-lasting weather protection.",
    lowStockThreshold: 5,
  },
  {
    id: "p2",
    name: "Royale Luxury Emulsion",
    slug: "royale-luxury-emulsion-10l",
    brand: "Asian Paints",
    category: "Interior Paints",
    finish: "Luxury Sheen",
    size: "10",
    unit: "L",
    price: 5820,
    stock: 9,
    tintable: true,
    status: "active",
    isFeatured: true,
    isVisibleOnStorefront: true,
    shortDescription: "Premium interior finish with smooth richness and elegant depth.",
    lowStockThreshold: 4,
  },
  {
    id: "p3",
    name: "WeatherCoat Anti Dustt",
    slug: "weathercoat-anti-dustt-20l",
    brand: "Berger",
    category: "Exterior Paints",
    finish: "Smooth Matt",
    size: "20",
    unit: "L",
    price: 6180,
    stock: 6,
    tintable: true,
    status: "active",
    isFeatured: false,
    isVisibleOnStorefront: true,
    shortDescription: "Exterior paint designed for strong weather resistance.",
    lowStockThreshold: 5,
  },
  {
    id: "p4",
    name: "Interior Primer",
    slug: "interior-primer-20l",
    brand: "Nerolac",
    category: "Primers",
    finish: "Base Coat",
    size: "20",
    unit: "L",
    price: 2950,
    stock: 14,
    tintable: false,
    status: "active",
    isFeatured: false,
    isVisibleOnStorefront: true,
    shortDescription: "Reliable primer coat for improved surface preparation.",
    lowStockThreshold: 5,
  },
  {
    id: "p5",
    name: "Wall Putty",
    slug: "wall-putty-20kg",
    brand: "Birla White",
    category: "Putty",
    finish: "Smooth Base",
    size: "20",
    unit: "kg",
    price: 780,
    stock: 30,
    tintable: false,
    status: "active",
    isFeatured: false,
    isVisibleOnStorefront: true,
    shortDescription: "Smooth wall preparation for better paint finish and coverage.",
    lowStockThreshold: 10,
  },
  {
    id: "p6",
    name: 'Synthetic Enamel',
    slug: "synthetic-enamel-4l",
    brand: "Dulux",
    category: "Interior Paints",
    finish: "Gloss",
    size: "4",
    unit: "L",
    price: 1740,
    stock: 11,
    tintable: true,
    status: "active",
    isFeatured: true,
    isVisibleOnStorefront: true,
    shortDescription: "Glossy enamel finish suitable for trim, metal, and wood surfaces.",
    lowStockThreshold: 4,
  },
];